### ISSUE TITLE
Failed to load the atom-xmlvalidate package

### ISSUE THREAD

**Issue by distinctgrey** [pdavies011010/atom-xmlvalidate#6]
Steps to reproduce:

1. Open Atom (with no open windows)
2. See error appear instantly

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-xmlvalidate](https://github.com/pdavies011010/atom-xmlvalidate) package 0.4.0

### Stack Trace

Failed to load the atom-xmlvalidate package

```
At Could not locate the bindings file. Tried:
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/Debug/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/Release/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/out/Debug/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/Debug/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/out/Release/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/Release/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/default/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/compiled/7.4.0/darwin/x64/xmljs.node

Error: Could not locate the bindings file. Tried:
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/Debug/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/Release/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/out/Debug/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/Debug/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/out/Release/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/Release/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/build/default/xmljs.node
 → /Users/thomas/.atom/packages/atom-xmlvalidate/compiled/7.4.0/darwin/x64/xmljs.node
    at bindings (/packages/atom-xmlvalidate/node_modules/bindings/bindings.js:88:9)
    at /packages/atom-xmlvalidate/node_modules/libxmljs-mt/lib/bindings.js:1:192)
    at /packages/atom-xmlvalidate/node_modules/libxmljs-mt/lib/bindings.js:3:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-xmlvalidate/node_modules/libxmljs-mt/index.js:4:16)
    at /packages/atom-xmlvalidate/node_modules/libxmljs-mt/index.js:43:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-xmlvalidate/lib/atom-xmlvalidate.js:11:22)
    at /packages/atom-xmlvalidate/lib/atom-xmlvalidate.js:312:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
```

### Commands

```
     -0:04.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
api-workbench 0.8.47 
atom-beautify 0.30.5 
atom-xmlvalidate 0.4.0 
autoclose-html 0.23.0 
autocomplete-xml 0.9.4 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.11 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-velocity 0.1.2 
linter 2.2.0 
linter-ui-default 1.6.8 
raml 0.2.0 
```

**Comment by pdavies011010** [comment]
Thanks @distinctgrey I have seen this error before and will be glad to look into it. For starters, could you tell me if the xmljs.node file does exist in any of the paths it mentions (/Users/thomas/.atom/packages/atom-xmlvalidate/build/, etc. etc.) ? Thanks!

**Comment by distinctgrey** [comment]
Hi @pdavies011010 - thanks for taking a look.

Here's the contents of the atom-xmlvalidate folder:

```
thomas@tdgmbpn5 ~ $ ls ~/.atom/packages/atom-xmlvalidate/
total 272
drwxr-xr-x   15 thomas  staff   510B Sep 18 10:52 ./
drwxr-xr-x   18 thomas  staff   612B Sep 18 10:52 ../
-rw-r--r--    1 thomas  staff   280B Sep  6 10:31 .eslintrc.json
-rw-r--r--    1 thomas  staff    37B Sep  6 10:31 .npmignore
-rw-r--r--    1 thomas  staff    65B Sep  6 10:31 CHANGELOG.md
drwxr-xr-x    3 thomas  staff   102B Sep  6 10:31 keymaps/
drwxr-xr-x    4 thomas  staff   136B Sep  6 10:31 lib/
-rw-r--r--    1 thomas  staff   1.0K Sep  6 10:31 LICENSE.md
drwxr-xr-x    3 thomas  staff   102B Sep  6 10:31 menus/
drwxr-xr-x  113 thomas  staff   3.8K Sep  6 10:31 node_modules/
-rw-r--r--    1 thomas  staff   105K Sep  6 10:31 package.json
-rw-r--r--    1 thomas  staff   2.0K Sep  6 10:31 README.md
drwxr-xr-x    4 thomas  staff   136B Sep  6 10:31 spec/
drwxr-xr-x    3 thomas  staff   102B Sep  6 10:31 styles/
```

As you can see, none of the folders that are scanned for `xmljs.node` exist.
Does that help you?

**Comment by pdavies011010** [comment]
Okay, yes it does, thanks Thomas. It looks like the build didn't run at all. If you look under the installation instructions (https://github.com/pdavies011010/atom-xmlvalidate#installation) there are specific instructions for MacOs. Namely the requirements for node-gyp (https://github.com/nodejs/node-gyp#installation) are that you'll need node/npm/python2 installed as well as the XCode and the XCode command line tools (the instructions for that are on the node-gyp install page linked above). Did you install all of that?

**Comment by distinctgrey** [comment]
Oh, I see now. I interpreted the installation instructions as "by installing this package you will automatically install libxml and node-gyp" - sorry for the hassle.

Maybe you could improve the error to something like "Could not locate the bindings file. Did you install this package's required dependencies?" or even better, refuse to install without all necessary dependencies?

**Comment by pdavies011010** [comment]
Sorry for the delay. There are too many issues with building this module due to it's use of a native (C/C++) XML validation library. I am looking at recreating the module using something like https://www.npmjs.com/package/xmllint now, which is pure javascript and won't have the same build dependency issues. I will update when that work is done.
