### ISSUE TITLE
Failed to activate the atom-xmlvalidate package

### ISSUE THREAD

**Issue by worldsayshi** [pdavies011010/atom-xmlvalidate#7]
I think I haven't been able to use atom-xmlvalidate since I updated node. Now I tried to rebuild the package by Atom's prompt and got this error. Seems this package doesn't support newer node.js?

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-xmlvalidate](https://github.com/pdavies011010/atom-xmlvalidate) package 0.4.0

### Stack Trace

Failed to activate the atom-xmlvalidate package

```
At The module '/home/perfre/.atom/packages/atom-xmlvalidate/node_modules/libxmljs/build/Release/xmljs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

Error: The module '/home/perfre/.atom/packages/atom-xmlvalidate/node_modules/libxmljs/build/Release/xmljs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at bindings (/packages/atom-xmlvalidate/node_modules/bindings/bindings.js:76:44)
    at /packages/atom-xmlvalidate/node_modules/libxmljs/lib/bindings.js:1:192)
    at /packages/atom-xmlvalidate/node_modules/libxmljs/lib/bindings.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-xmlvalidate/node_modules/libxmljs/index.js:4:16)
    at /packages/atom-xmlvalidate/node_modules/libxmljs/index.js:43:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-xmlvalidate/lib/atom-xmlvalidate.js:11:22)
    at /packages/atom-xmlvalidate/lib/atom-xmlvalidate.js:312:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-hot-package-loader 0.5.1 
atom-ide-ui 0.5.4 
atom-ternjs 0.18.3 
atom-xmlvalidate 0.4.0 
atomic-chrome 0.3.3 
auto-reveal-in-sidebar 0.8.0 
autoclose-html 0.23.0 
autocomplete-paths 2.12.1 
blame 0.12.0 
build 0.69.0 
busy-signal 1.4.3 
compare-files 0.8.1 
counter 0.3.5 
ctags-status 1.3.7 
custom-title 1.0.1 
git-blame 1.3.1 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.10.0 
goto-definition 1.3.4 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
hyperclick 0.0.0 
ide-typescript 0.7.0 
intentions 1.1.5 
js-hyperclick 1.12.2 
jsonlint 1.1.4 
keyboard-localization 1.5.0 
language-babel 2.78.0 
language-groovy 0.7.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-eslint 8.4.0 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
linter-xo 0.23.1 
markdown-preview-plus 2.4.16 
pretty-json 1.6.4 
react 0.17.0 
react-snippets 1.0.0 
select-rectangle 1.0.2 
tabs-to-spaces 1.0.3 
tree-view-copy-relative-path 1.2.0 
xml-formatter 0.11.0 
```

**Comment by pdavies011010** [comment]
Hey @worldsayshi , 
libxmljs is a native package and such is tied a specific nodejs build version, but that doesn't mean it won't work a specific build of node, just that the dependency needs to be built against whatever version of node you're running. 

Unfortunately it sounds like when atom prompted you to update the atom-xmlvalidate package it didn't automatically rebuild libxmljs for you, but you should be able to do so manually. Try this: 

`cd /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/libxmljs; rm -R build\Release; npm install;`
     

After that you may need to go back into your atom settings to reactivate the package (what you tried to do before), but hopefully it should work. 

I wish I had the time to write a pure javascript XML validator so I could replace libxmljs, which works well but introduces all of this build pain. There are several pure js XML parsers out there but no validators, so for the time being this is the best I could come up with, in any case hopefully the commands above will get you working again, let me know. 
Thanks!
Phill

**Comment by worldsayshi** [comment]
Atom did prompt me to re-build earlier and I did. This was before the error above if I remember correctly. I tried to rebuild again with your instructions. The error, pasted below, is now a bit different. 

I will deactivate the package for now. Will see when I have time to look into it again.

```
Could not locate the bindings file. Tried:
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/Debug/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/Release/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/out/Debug/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/Debug/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/out/Release/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/Release/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/default/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/compiled/7.4.0/linux/x64/xmljs.node
Hide Stack Trace
Error: Could not locate the bindings file. Tried:
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/Debug/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/Release/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/out/Debug/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/Debug/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/out/Release/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/Release/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/build/default/xmljs.node
 → /home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/compiled/7.4.0/linux/x64/xmljs.node
    at bindings (/home/perfre/.atom/packages/atom-xmlvalidate/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/perfre/.atom/packages/atom-xmlvalidate/node_modules/libxmljs/lib/bindings.js:1:192)
    at Object.<anonymous> (/home/perfre/.atom/packages/atom-xmlvalidate/node_modules/libxmljs/lib/bindings.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/perfre/.atom/packages/atom-xmlvalidate/node_modules/libxmljs/index.js:4:16)
    at Object.<anonymous> (/home/perfre/.atom/packages/atom-xmlvalidate/node_modules/libxmljs/index.js:43:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/perfre/.atom/packages/atom-xmlvalidate/lib/atom-xmlvalidate.js:11:22)
    at Object.<anonymous> (/home/perfre/.atom/packages/atom-xmlvalidate/lib/atom-xmlvalidate.js:312:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:903:35)
```

**Comment by worldsayshi** [comment]
Hmm, I found a thread that seems very related: https://github.com/libxmljs/libxmljs/issues/253

Could be that I changed the permissions by manually building the package. Hmm. Well, will need to look into it at a later time.

**Comment by pdavies011010** [comment]
Yeah, I've definitely seen that error before during development, where even though the xmljs.node bindings file is there in one of the paths it searches, it can't seem to "find" it. You could be right, might be a permissions issue. If I remember correctly the issue for me was that I was running a 32-bit version of atom/electron but rebuilt the package using a 64-bit version of node. Again... this is the pain of having to use a native module rather than a pure javascript one. 

I think my next free time project will have to be writing a javascript replacement for libxmljs...    now I just need some free time!

**Comment by pdavies011010** [comment]
Sorry for the delay. There are too many issues with building this module due to it's use of a native (C/C++) XML validation library. I am looking at recreating the module using something like https://www.npmjs.com/package/xmllint now, which is pure javascript and won't have the same build dependency issues. I will update when that work is done.
